name: 同步IPBD

on:
  schedule:
    - cron: '0 */4 * * *'  # 每四小时运行一次
  workflow_dispatch:  # 允许手动触发
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install requests module
      run: pip install requests

    - name: Run Python script
      run: python ipbd.py
