name: Sync Files

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小时执行一次，详细的定时规则可根据需求调整
  workflow_dispatch:  # 手动触发器，允许手动执行工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Download addressesapi.txt from Repo B
        run: |
          wget -O addressesapi.txt https://raw.githubusercontent.com/cmliu/WorkerVless2sub/main/addressesapi.txt

      - name: Download addressescsv.csv from Repo B
        run: |
          wget -O addressescsv.csv https://raw.githubusercontent.com/cmliu/WorkerVless2sub/main/addressescsv.csv

      - name: Copy addressesapi.txt to yxip.txt
        run: |
          cp addressesapi.txt ./yxip.txt

      - name: Copy addressescsv.csv to yxipcsv.csv
        run: |
          cp addressescsv.csv ./yxipcsv.csv
