name: Sync Files

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小时执行一次，详细的定时规则可根据需求调整
  workflow_dispatch:  # 手动触发器，允许手动执行工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v2.5.0

      - name: Download Files from Repo B
        run: |
          wget -O addressesapi.txt https://raw.githubusercontent.com/cmliu/WorkerVless2sub/main/addressesapi.txt
          wget -O addressescsv.csv https://raw.githubusercontent.com/cmliu/WorkerVless2sub/main/addressescsv.csv

      - name: Copy addressesapi.txt to Repo A
        run: cp addressesapi.txt ./yxip.txt

      - name: Copy addressescsv.csv to Repo A
        run: cp addressescsv.csv ./yxipcsv.csv

      - name: Store File Paths in Environment File
        run: |
          echo "YXIP_FILE_PATH=./yxip.txt" >> $GITHUB_ENV
          echo "YXIPCSV_FILE_PATH=./yxipcsv.csv" >> $GITHUB_ENV

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: '同步CM优选ip'
          add: "['yxip.txt', 'yxipcsv.csv']"
