name: Sync Files

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次，详细的定时规则可根据需求调整

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2
        with:
          repository: cmliu/WorkerVless2sub

      - name: Copy Files from Repo B to Repo A
        run: |
          cp addressesapi.txt ../yxip/yxip.txt
          cp addressescsv.csv ../yxip/yxipcsv.csv

      - name: Commit and Push Changes to Repo A
        run: |
          cd ../yxip
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "同步CM优选ip"
          git push
