name: Sync Files

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小时执行一次，详细的定时规则可根据需求调整
  workflow_dispatch:  # 手动触发器，允许手动执行工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "1234@gmail.com"
          git config --global user.name "djwppm"

      - name: Initialize Git Repository
        run: git init

      - name: Download Files from Repo B
        run: |
          wget -O addressesapi.txt https://raw.githubusercontent.com/cmliu/WorkerVless2sub/main/addressesapi.txt
          wget -O addressescsv.csv https://raw.githubusercontent.com/cmliu/WorkerVless2sub/main/addressescsv.csv

      - name: Copy addressesapi.txt to Repo A
        run: |
          cp addressesapi.txt ./yxip.txt

      - name: Copy addressescsv.csv to Repo A
        run: |
          cp addressescsv.csv ./yxipcsv.csv

      - name: Show Contents of Repo A
        run: |
          ls -l
          cat yxip.txt
          cat yxipcsv.csv

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Sync files from Repo B"

      - name: Push Changes
        run: |
          git remote add origin https://github.com/qfsy/yxip.git
          git branch -M main
          git push -u origin main
