name: Sync Files

on:
  schedule:
    - cron: '0 */4 * * *'  # 每 4 小时执行一次，详细的定时规则可根据需求调整
  workflow_dispatch:  # 手动触发器，允许手动执行工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v2
        with:
          repository: cmliu/WorkerVless2sub

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Debugging
        run: pwd  # 输出当前目录的路径

      - name: Copy Files from Repo B to Repo A
        run: |
          cp addressesapi.txt ../yxip/yxip.txt
          cp addressescsv.csv ../yxip/yxipcsv.csv

      - name: Commit and Push Changes to Repo A
        run: |
          cd ../yxip
          git add .
          git commit -m "同步CM优选ip"
          git push
